name: scribes
description: A command line tool for generating consitent data objects in Typescript and Dart.
version: 0.0.1-dev.1
repository: https://github.com/mtwichel/scribes
homepage: https://github.com/mtwichel/scribes
issue_tracker: https://github.com/mtwichel/scribes/issues

environment:
  sdk: ">=2.8.1 <3.0.0"

dependencies:
  very_good_analysis: ^1.0.4
  equatable: ^1.2.6
  json_annotation: ^3.0.1
  recase: ^3.0.1
  checked_yaml: ^1.0.4
  meta: ^1.2.4
  args: ^1.6.0
  io: ^0.3.4
  yaml: ^2.2.1

dev_dependencies:
  coverage: ^0.14.2
  json_serializable: ^3.3.0
  build_verify: ^1.1.1
  build_version: ^2.0.1
  mockito: ^4.0.0
  test: ^1.14.3
  build_runner: ^1.10.0

executables:
  scribe:
